akgul_yemek-master/yedek/Akgul_Yemek/Akgul_Yemek/Models/slider.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akgul_Yemek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slider
    {
        public int id { get; set; }
        public string filename { get; set; }
        public string keywords { get; set; }
    }
}

akgul_yemek-master/yedek/Akgul_Yemek/Akgul_Yemek/Controllers/Admin_SiteController.cs
using Akgul_Yemek.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Akgul_Yemek.Code;

namespace Akgul_Yemek.Controllers
{
    public class Admin_SiteController : Controller
    {
        //
        // GET: /Admin_Site/

        #region STATISTICS

        public ActionResult Index()
        {
            akgul_yemek_dbEntities db = new akgul_yemek_dbEntities();

            // assing statistics
            Site_Istatistik_Model admin_istatistik = new Site_Istatistik_Model()
            {
                username = Session["name"].ToString(),
                food_count = db.site_food_menu.Count(),
                gallery_count = db.gallery_titles.Count(),
                menu_count = db.site_menu.Count(),
                slider_count = db.slider.Count()
            };

            ViewData["statistics"] = admin_istatistik;



            //Navigation______________________________________________________
            List<NavigationModel> navList = new List<NavigationModel>() 
            { 
                
            };
            ViewData["navigation"] = navList;
            //________________________________________________________________



            return View();
        }

        #endregion


        #region SLIDER

        public ActionResult Slider()
        {
            akgul_yemek_dbEntities db = new akgul_yemek_dbEntities();
            List<slider> sliders = db.slider.ToList();
            ViewData["sliders"] = sliders;

            //Navigation______________________________________________________
            List<NavigationModel> navList = new List<NavigationModel>() 
            { 
                new NavigationModel(){name="SLIDER",url=""}
            };
            ViewData["navigation"] = navList;
            //________________________________________________________________


            return View();
        }

        [HttpPost]
        public ActionResult Transition_SliderEkle(FormCollection formCollection)
        {
            int random_number = new Random().Next(0, 1024);

            try
            {
                slider slide = (slider)MTranslation.BuildObject(formCollection, "slider");

                // adding picture to Disk
                HttpPostedFileBase file = Request.Files[0];
                if (file.ContentLength > 0)
                {
                    string filename = Path.GetFileName(file.FileName);
                    string path = Path.Combine(Server.MapPath("~/Files/Slider"), "" + random_number + filename);
                    file.SaveAs(path);

                    // food image_name is uploaded picture name
                    slide.filename = "" + random_number + filename;
                    slide.keywords = "akgül yemek,akgül organizasyon,akgül";

                    // adding food to Database
                    akgul_yemek_dbEntities db = new akgul_yemek_dbEntities();

                    db.slider.Add(slide);
                    db.SaveChanges();

                    Session["message"] = new MessageModel("Bilgi", "Slayt Resmi Ekendi.", Message_Type.Success);
                    return RedirectToAction("Slider");

                }
                else
                {
                    MLog.Error("Slayt Resmi Ekenemedi.", "Slider Fotoğraf Yüklenemedi");
                    Session["message"] = new MessageModel("HATA", "Slider Fotoğraf Yüklenemedi", Message_Type.Error);

                    return RedirectToAction("Slider");
                }
            }
            catch (Exception exception)
            {
                MLog.Error("Slider Fotoğraf Yüklenemedi", exception.Message + Environment.NewLine + exception.StackTrace);
                Session["message"] = new MessageModel("HATA", "Bir hata oluştu.", Message_Type.Error);

                return RedirectToAction("Slider");
            }
        }

        public ActionResult Transition_SliderSil(string id)
        {
            try
            {
                int slide_id = Convert.ToInt32(id);

                akgul_yemek_dbEntities db = new akgul_yemek_dbEntities();
                slider slide = db.slider.Where(w => w.id == slide_id).FirstOrDefault();
                if (slide != null)
                {
                    //deleting picture from disk
                    string file_path = Path.Combine(Server.MapPath("~/Files/Slider"), slide.filename);
                    if (System.IO.File.Exists(file_path))
                        System.IO.File.Delete(file_path);

                    // deleting from database
                    db.slider.Remove(slide);
                    db.SaveChanges();

                    Session["message"] = new MessageModel("Bilgi", "Slayt Resmi Silindi.", Message_Type.Success);
                    return RedirectToAction("Slider");
                }
                else
                {
                    MLog.Error("Slayf Resmi Silinemedi.", "Belirtilen Resim Bulunamadı.");
                    Session["message"] = new MessageModel("Slayt Resmi Silinemedi", "Belirtilen Resim Bulunamadı.", Message_Type.Error);

                    return RedirectToAction("Slider");
                }
            }
            catch (Exception exception)
            {
                MLog.Error("Slayt Resmi Silinemedi", exception.Message + Environment.NewLine + exception.StackTrace);
                Session["message"] = new MessageModel("HATA", "Bir hata oluştu.", Message_Type.Error);

                return RedirectToAction("Slider");
            }
        }


        #endregion


        #region MENU

        public ActionResult Menu_Listele()
        {
            akgul_yemek_dbEntities db = new akgul_yemek_dbEntities();

            List<site_menu> site_menu_s = db.site_menu.ToList();
            ViewData["site_menu_s"] = site_menu_s;


            //Navigation______________________________________________________
            List<NavigationModel> navList = new List<NavigationModel>() 
            { 
                new NavigationModel(){name="MENÜLER",url=""}
            };
            ViewData["navigation"] = navList;
            //________________________________________________________________


            return View();
        }


        public ActionResult Menu_Detay(string id)
        {
            int menu_id = Convert.ToInt32(id);

            akgul_yemek_dbEntities db = new akgul_yemek_dbEntities();

            site_menu _site_menu = db.site_menu.Where(w => w.id == menu_id).FirstOrDefault();
            ViewData["site_menu"] = _site_menu;

            List<site_food_menu> site_foods = db.site_food_menu.Where(w => w.site_menu_id == menu_id).ToList();
            ViewData["site_foods"] = site_foods;



            //Navigation______________________________________________________
            List<NavigationModel> navList = new List<NavigationModel>() 
            { 
                new NavigationModel(){name="MENÜLER",url="/Admin_Site/Menu_Listele"},
                new NavigationModel(){name="MENÜ DETAY",url=""}
            };
            ViewData["navigation"] = navList;
            //________________________________________________________________


            return View();
        }

        [HttpPost]
        public ActionResult Transition_MenuEkle(FormCollection formCollection)
        {
            try
            {
                site_menu _site_menu = (site_menu)MTranslation.BuildObject(formCollection, "site_menu");

                akgul_yemek_dbEntities db = new akgul_yemek_dbEntities();
                if (_site_menu.name != "")
                {
                    db.site_menu.Add(_site_menu);
                    db.SaveChanges();

                    Session["message"] = new MessageModel("Bilgi", "Menü Ekendi.", Message_Type.Success);
                    return RedirectToAction("Menu_Listele");
                }
                else
                {
                    Session["message"] = new MessageModel("Menü Eklenemedi.", "Eksik Bilgi Girildi.", Message_Type.Error);
                    MLog.Error("Menü Eklenemedi.", "Eksik Bilgi Girildi.");

                    return RedirectToAction("Menu_Listele");
                }
            }
            catch (Exception exception)
            {
                MLog.Error("Menü Ekenemedi.", exception.Message + Environment.NewLine + exception.StackTrace);
                Session["message"] = new MessageModel("HATA", "Bir hata oluştu.", Message_Type.Error);

                return RedirectToAction("Menu_Listele");
            }
        }


        public ActionResult Transition_MenuSil(string id)
        {
            try
            {
                int menu_id = Convert.ToInt32(id);

                akgul_yemek_dbEntities db = new akgul_yemek_dbEntities();
                site_menu _site_menu = db.site_menu.Where(w => w.id == menu_id).FirstOrDefault();
                if (_site_menu != null)
                {
                    db.site_menu.Remove(_site_menu);
                    db.SaveChanges();

                    Session["message"] = new MessageModel("Bilgi", "Menü Silindi.", Message_Type.Success);
                    return RedirectToAction("Menu_Listele");
                }
                else
                {
                    MLog.Error("Menü Silinemedi.", "Belirtilen Menu Bulunamadı.");
                    Session["message"] = new MessageModel("HATA", "Belirtilen Menu Bulunamadı.", Message_Type.Error);

                    return RedirectToAction("Menu_Listele");
                }
            }
            catch (Exception exception)
            {
                MLog.Error("Menü Silinemedi.", exception.Message + Environment.NewLine + exception.StackTrace);
                Session["message"] = new MessageModel("HATA", "Bir hata oluştu.", Message_Type.Error);

                return RedirectToAction("Menu_Listele");
            }
        }


        [HttpPost]

akgul_yemek-master/yedek/Akgul_Yemek/Akgul_Yemek/Views/Admin_Site/Galeri_Detay.cshtml
@{
    ViewBag.Title = "Akgül Yemek - Galeri Detay";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

@using Akgul_Yemek.Models

@{
    gallery_titles albume = (gallery_titles)ViewData["albume"];
    List<gallery_images> albume_images = (List<gallery_images>)ViewData["albume_images"];   
}


<div class="col-md-8">
    
    <div class=" panel panel-primary">
        <div class="panel-body">
            <form action="/Admin_Site/Transition_GaleriTitleGuncelle" method="post">

                <input type="hidden" name="id" value="@albume.id" />

                <div class="input-group">
                    <span class="input-group-addon" id="sizing-addon1">Galeri Adı</span>
                    <input name="title" type="text" class="form-control" value="@albume.title" placeholder="Galeri Adı Girin..">
                </div><!-- /input-group -->

                <div class="input-group" style="margin-top:10px;">
                    <span class="input-group-addon" id="sizing-addon1">&nbsp; Etiketler&nbsp;</span>
                    <input name="keywords" type="text" class="form-control" value="@albume.keywords" placeholder="Etiketler..">
                </div><!-- /input-group -->
                <br />
                <button class="btn btn-success" type="submit">GÜNCELLE</button>
            </form>

        </div>
    </div>



    <hr />



    @using (Html.BeginForm("Transition_GaleriResimEkle", "Admin_Site", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        <input type="hidden" name="title_id" value="@albume.id" />

        <div class="panel panel-primary">
            <div class="panel-heading" style="font-size:20px;">
                <label>GALERİYE FOTOĞRAF YÜKLE</label>
            </div>
            <div class="panel-body" style="font-size:15px;">
                <div class="input-group">
                    <h4>Cihazınızdan Resim Yükleyin</h4>
                    <input class="form-control-file" type="file" name="picture" accept="image/*"><br />
                    <hr style="border: solid 1px black;"/>
                    <h4>VEYA Yotube'dan Video Yükleyin</h4>
                    <input type="text" name="videoUrl" class="form-control" placeholder="Video Url" />
                    <br /><br />
                    <hr style="border: solid 1px black;" />
                    <br />

                    <input class="btn btn-success" type="submit" value="&nbsp;&nbsp; YÜKLE &nbsp;&nbsp;">
                </div>
            </div>
        </div>


    }

    <hr />


    <div class=" panel panel-primary">
        <div class="panel-heading" style="font-size:20px;">@albume.title albümüne ait fotoğraflar</div>

        <div class="panel-body">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Fotoğraf/Video</th>
                    <th>Sil</th>
                </tr>
                </thead>
                <tbody>

                @foreach (gallery_images gimage in albume_images)
                {
                    string content_type = (gimage.file_name.Contains(".")) ? "image" : "video";
                    string image_src = "";
                    if (content_type == "image")
                    {
                        image_src = "Files/Galleries/" + albume.id + "/" + gimage.file_name;
                    }
                    else if (content_type == "video")
                    {
                        image_src = "Files/Galleries/video.png";
                    }
                    
                    <tr>
                        <td><img src="~/@image_src"/></td>
                        <td>
                            <a class="btn btn-lg btn-danger" data-toggle="confirmation" data-title="Fotoğraf/Video Silinsin mi?"
                               href="/Admin_Site/Transition_GaleriResimSil/@gimage.id" data-btn-ok-label="Evet" data-btn-cancel-label="Hayır">Sil</a>
                        </td>
                    </tr>
                }


                </tbody>
            </table>

            <br/>
            <br/>
        </div>
    </div>
</div>

akgul_yemek-master/yedek/Akgul_Yemek/Akgul_Yemek/Views/Admin_Site/Galeri_Kategori_Detay.cshtml
@{
    ViewBag.Title = "Akgül Yemek - Galeri Listele";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

@using Akgul_Yemek.Models

@{
    List<gallery_titles> albume_list = (List<gallery_titles>)ViewData["gallery_titles"];
    gallery_categories this_albume_category = (gallery_categories)ViewData["gallery_category"];
}


<div class="col-md-8">

    
    <div class="row" style="margin:1px;">

        <div class="panel panel-primary">
            <!-- Default panel contents -->
            <div class="panel-heading">GALERİ EKLE</div>

            <div class="panel-body">
                <form action="/Admin_Site/Transition_GaleriTitleEkle" method="post">
                    <div class="input-group">

                        <input type="hidden" name="category_id" value="@this_albume_category.id" />
                        <input name="title" type="text" class="form-control" style="margin: 10px;" placeholder=" Galeri Adı Girin..">


                        <input name="keywords" type="text" class="form-control" style="margin: 10px;" placeholder="Anahtar Kelimeler Girin..">
                    </div>


                    <button class="btn btn-success" style="margin: 10px;" type="submit">Galeriyi Kaydet</button>
                </form>
            </div>
        </div>


        <hr />
        <br />
        <br />

        <div class="panel panel-primary">
            <!-- Default panel contents -->
            <div class="panel-heading">Galeriler</div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Galeri Adı</th>
                        <th>İşlem</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < albume_list.Count; i++)
                    {
                        gallery_titles albume = albume_list.ElementAt(i);

                        <tr>
                            <td>@albume.title</td>
                            <td>
                                <a class="btn btn-danger" data-toggle="confirmation" data-title="Galeri Silinsin mi?"
                                   href="/Admin_Site/Transition_GaleriTitleSil/@albume.id" data-btn-ok-label="Evet" data-btn-cancel-label="Hayır">Sil</a>
                                <a class="btn btn-warning" href="/Admin_Site/Galeri_Detay/@albume.id">Düzenle</a>
                            </td>
                        </tr>

                    }


                </tbody>
            </table>
        </div>
    </div><!-- /.row -->

</div><!-- /.col- -->

akgul_yemek-master/yedek/Akgul_Yemek/Akgul_Yemek/Views/Admin_Site/Galeri_Listele.cshtml
@{
    ViewBag.Title = "Akgül Yemek - Galeri Listele";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

@using Akgul_Yemek.Models

@{
    List<gallery_categories> albume_category_list = (List<gallery_categories>)ViewData["g_categories"];
}


<div class="col-md-8">

    <div class="row" style="margin:1px;">

        <div class="panel panel-primary">
            <!-- Default panel contents -->
            <div class="panel-heading">GALERİ KATEGORİSİ EKLE</div>
            <div class="panel-body">
                <form action="/Admin_Site/Transition_GaleriKategoriEkle" method="post">
                    <div class="input-group">
                        <input name="name" type="text" class="form-control" style="margin: 10px;" placeholder=" Kategori Adı Girin..">
                    </div>

                    <button class="btn btn-success" style="margin: 10px;" type="submit">Galeriyi Kaydet</button>
                </form>
            </div>
        </div>


        <hr />
        <br />
        <br />

        <div class="panel panel-primary">
            <!-- Default panel contents -->
            <div class="panel-heading">Galeriler</div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Kategori Adı</th>
                        <th>İşlem</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < albume_category_list.Count; i++)
                    {
                        gallery_categories albumeCategory = albume_category_list.ElementAt(i);

                        <tr>
                            <td>@albumeCategory.name</td>
                            <td>
                                <a class="btn btn-danger" data-toggle="confirmation" data-title="Galeri Silinsin mi?"
                                   href="/Admin_Site/Transition_GaleriKategoriSil/@albumeCategory.id" data-btn-ok-label="Evet" data-btn-cancel-label="Hayır">Sil</a>
                                <a class="btn btn-warning" href="/Admin_Site/Galeri_Kategori_Detay/@albumeCategory.id">Düzenle</a>
                            </td>
                        </tr>

                    }


                </tbody>
            </table>
        </div>
    </div><!-- /.row -->

</div><!-- /.col- -->

akgul_yemek-master/yedek/Akgul_Yemek/Akgul_Yemek/Views/Admin_Site/Icerik.cshtml
@{
    ViewBag.Title = "Icerik";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";

    string content_type = (string)ViewData["id"];
    string content = (string)ViewData["content"];

    string isenabled_hakkimizda = "", isenabled_sertifikalarimiz = "", isenabled_hizmetlerimiz = "", isenabled_insankaynaklari = "";
    string caption = "";

    switch (content_type)
    {
        case "hakkimizda":
            isenabled_hakkimizda = "selected";
            caption = "HAKKIMIZDA";
            break;
        case "sertifikalarimiz":
            isenabled_sertifikalarimiz = "selected";
            caption = "SERTİFİKALARIMIZ";
            break;
        case "hizmetlerimiz":
            isenabled_hizmetlerimiz = "selected";
            caption = "HİZMETLERİMİZ";
            break;
        case "insankaynaklari":
            isenabled_insankaynaklari = "selected";
            caption = "İNSAN KAYNAKLARI";
            break;


        default:
            break;
    }

}

<div class="col-md-8">

    <div class=" panel panel-primary">
        <div class="panel-body">

            <form method="get" action="/Admin_Site/Icerik">
                <label>Düzenlenecek İçeriğin Adı: </label>
                <select class="form-control" id="id" name="id">
                    <option @isenabled_hakkimizda value="hakkimizda">HAKKIMIZDA</option>
                    <option @isenabled_sertifikalarimiz value="sertifikalarimiz">SERTİFİKALARIMIZ</option>
                    <option @isenabled_hizmetlerimiz value="hizmetlerimiz">HİZMETLERİMİZ</option>
                    <option @isenabled_insankaynaklari value="insankaynaklari">İNSAN KAYNAKLARI</option>
                </select>
                <br />
                <input type="submit" class="btn btn-block btn-success" value="İÇERİĞİ GETİR" />
            </form>

        </div>
    </div>

    <div class=" panel panel-primary">
        <div class="panel-body">

            <form action="/Admin_Site/Transition_IcerikGuncelle" method="post">

                <input type="hidden" name="key_" value="@content_type" />

                <label>İçerik: @caption</label>

                <hr style="border:solid 1px black;" />

                <textarea name="value" id="value" class="ckeditor">@content</textarea>

                <script>
                    CKEDITOR.replace('value');
                </script>

                <hr style="border:solid 1px black;" />

                <input type="submit" class="btn btn-block btn-primary" value="KAYDET" />

            </form>
        </div>
    </div>


</div>

akgul_yemek-master/yedek/Akgul_Yemek/Akgul_Yemek/Views/Admin_Site/Iletisim.cshtml
@{
    ViewBag.Title = "Iletisim";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

@using Akgul_Yemek.Models

@{
    Iletisim_Model iletisim_model = (Iletisim_Model)ViewData["iletisim_model"];
}

<div class="col-md-8">

    
    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading">Iletisim Bilgileri Güncelle</div>

        <form class="form-horizontal" action="/Admin_Site/Transition_IletisimBilgileriniGuncelle" method="post" style="padding:15px;">
            <div class="">
                <label for="telefon">Telefon - 1</label>
                <input name="tel1" type="text" class="form-control" value="@iletisim_model.tel1" id="telefon">
            </div>
            <div class="">
                <label for="telefon">Telefon - 2</label>
                <input name="tel2" type="text" class="form-control" value="@iletisim_model.tel2" id="telefon">
            </div>
            <div class="">
                <label for="mail">E-mail:</label>
                <input name="email" type="text" class="form-control" value="@iletisim_model.email" id="mail">
            </div>
            <div class="">
                <label for="Adres">Adres:</label>
                <textarea name="address" class="form-control" rows="5" id="Adres">@iletisim_model.address</textarea>
            </div>
            <br /><br />
            <button type="submit" class="btn btn-success">Güncelle</button>
        </form>
        </div>
    </div>

akgul_yemek-master/yedek/Akgul_Yemek/Akgul_Yemek/Views/Admin_Site/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}
@using Akgul_Yemek.Models
@{
    Site_Istatistik_Model istatistik = (Site_Istatistik_Model)ViewData["statistics"];
}

<div class="panel panel-primary">
    <!-- Default panel contents -->
    <div class="panel-heading">İstatistikler</div>
    <div class="panel-body">


        <table class="table table-bordered">
            <thead>
                <tr class="info">
                    
                </tr>
            </thead>
            <tbody>
                <tr class="info">
                    <td>KULLANICI</td>
                    <td>@istatistik.username</td>
                </tr>
                <tr class="success">
                    <td>SLAYT SAYISI</td>
                    <td>@istatistik.slider_count</td>
                </tr>
                <tr class="info">
                    <td>MENU/YEMEK SAYISI</td>
                    <td>@istatistik.menu_count / @istatistik.food_count</td>
                </tr>
                <tr class="success">
                    <td>GALERİ SAYISI</td>
                    <td>@istatistik.gallery_count</td>
                </tr>
            </tbody>
        </table>

    </div>


</div>

akgul_yemek-master/yedek/Akgul_Yemek/Akgul_Yemek/Views/Admin_Site/Menu_Detay.cshtml
@{
    ViewBag.Title = "Akgül Yemek - Menu Detay";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

@using Akgul_Yemek.Models

@{
    site_menu _site_menu = (site_menu)ViewData["site_menu"];
    List<site_food_menu> site_foods = (List<site_food_menu>)ViewData["site_foods"];
}


<div class="col-md-8">

    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading">@_site_menu.name Menüsü</div>

        <div class="panel-body">


                @using (Html.BeginForm("Transition_MenuYemekEkle", "Admin_Site", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {

                    <input type="hidden" name="site_menu_id" value="@_site_menu.id" />

                    <div class="form-group">
                        <label for="yemekİsmi">Eklenecek Yemek ismi</label>
                        <input name="name" type="text" class="form-control" id="yemekİsmi">
                    </div>
                    <div class="form-group">
                        <label>Açıklama</label>
                        <input name="description" type="text" class="form-control" id="description">
                    </div>

                    <label for="picture" style="font-size:20px">Fotoğraf Yükleme</label>
                    <input type="file" name="picture" accept="image/*"><br />
                    <input class="btn btn-success" type="submit" value="Ekle">

                }

        </div>
    </div>

        <div class="panel panel-primary">
            <!-- Default panel contents -->
            <div class="panel-heading">@_site_menu.name Menüsünün İçindekiler</div>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Adı</th>
                        <th>Açıklama</th>
                        <th>Fotoğraf</th>
                        <th>Sil</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (site_food_menu site_food in site_foods)
                    {
                        <tr>
                            <td>@site_food.name</td>
                            <td>@site_food.description</td>
                            <td><img src="~/Files/Food_Menu/@site_food.image_name" /></td>
                            <td>
                                <a class="btn btn-lg btn-danger" data-toggle="confirmation" data-title="Yemek Silinsin mi?"
                                   href="/Admin_Site/Transition_MenuYemekSil/@site_food.id"  data-btn-ok-label="Evet" data-btn-cancel-label="Hayır">Sil</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

akgul_yemek-master/yedek/Akgul_Yemek/Akgul_Yemek/Views/Admin_Site/Slider.cshtml
@{
    ViewBag.Title = "Slider";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

@using Akgul_Yemek.Models

@{
    List<slider> sliders = (List<slider>)ViewData["sliders"];
}


<div class="col-md-8">
    
    @using (Html.BeginForm("Transition_SliderEkle", "Admin_Site", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        <div class="panel panel-primary">
            <div class="panel-heading" style="font-size:20px;">
                <label>SLAYT RESMİ YÜKLE</label>
            </div>
            <div class="panel-body" style="font-size:15px;">
                <div class="input-group">
                    <input class="form-control-file" type="file" name="picture" accept="image/*"><br />
                    <input class="btn btn-success" type="submit" value="&nbsp;&nbsp; YÜKLE &nbsp;&nbsp;">
                </div>
            </div>
        </div>
    }

    <hr />

    <br />
    <br />



    <div class="panel panel-primary">
        <!-- Default panel contents -->
        <div class="panel-heading">Aktif Fotoğraflar</div>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Fotoğraf</th>
                    <th>Sil</th>
                </tr>
            </thead>
            <tbody>
                
                @foreach (slider slide in sliders)
                {
                    <tr>
                        <td><img src="~/Files/Slider/@slide.filename" /></td>
                        <td>
                            <a class="btn btn-lg btn-danger" data-toggle="confirmation" data-title="Fotoğraf Silinsin mi?"
                               href="/Admin_Site/Transition_SliderSil/@slide.id" data-btn-ok-label="Evet" data-btn-cancel-label="Hayır">Sil</a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>